version: '3.8'

services:
  db:
    image: mariadb:11.1
    container_name: ap-minimal-db
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      # Komentariši init.sql posle prvog pokretanja
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: ap-minimal-web
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: ["./wait-for-it.sh", "db:3306", "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]

volumes:
  db_data:

